import { collection, getDocs, doc, updateDoc, query, where } from "https://www.gstatic.com/firebasejs/11.6.0/firebase-firestore.js";
import { db } from "./firebase-config.js";
import { setupLogoutButton, updateUserDisplay } from "./auth.js";
import { protectPage } from "./authGuard.js";
import { createPaginator } from "./pagination.js";

let currentDraftId = null;

// Pagination
const draftsPaginator = createPaginator({
    controlsEl: document.getElementById('draftsPagination'),
    renderFn: renderDraftCards,
    itemLabel: 'drafts'
});

const recipientsPaginator = createPaginator({
    controlsEl: document.getElementById('recipientsPagination'),
    renderFn: renderRecipientRows,
    itemLabel: 'recipients'
});

// Initialization
document.addEventListener("DOMContentLoaded", async () => {
    try {
        if (typeof lucide !== 'undefined') lucide.createIcons();
        const { user } = await protectPage(["Ketua Kampung"]);
        updateUserDisplay(user);
        setupLogoutButton();

        // Bind button events
        document.getElementById('closeDetailsBtn').addEventListener('click', closeDetails);
        document.getElementById('approveBtn').addEventListener('click', () => updateDraftStatus('Confirmed'));
        document.getElementById('rejectBtn').addEventListener('click', () => updateDraftStatus('Recalculation'));

        await fetchPendingDrafts();
    } catch (e) {
        console.error("Initialization error:", e);
    }
});

// Fetch pending drafts from Firestore
async function fetchPendingDrafts() {
    const container = document.getElementById('draftsListContainer');
    try {
        const q = query(collection(db, "welfareDrafts"), where("status", "==", "Pending Approval"));
        const snapshot = await getDocs(q);

        const drafts = [];
        snapshot.forEach(docSnap => drafts.push({ id: docSnap.id, data: docSnap.data() }));

        draftsPaginator.update(drafts, { resetLimit: true });
    } catch (error) {
        console.error("Error fetching drafts:", error);
        container.innerHTML = `<div style="color: #ef4444; padding: 1rem;">Failed to load drafts: ${error.message}</div>`;
    }
}

// Render a paginated slice of pending draft cards
function renderDraftCards(drafts) {
    const container = document.getElementById('draftsListContainer');
    container.innerHTML = '';

    if (drafts.length === 0) {
        container.innerHTML = '<div style="text-align: center; padding: 2rem; color: #94a3b8;">No pending drafts await your approval.</div>';
        return;
    }

    drafts.forEach(({ id, data }) => {
        const dateStr = new Date(data.createdAt).toLocaleDateString();

        const card = document.createElement('div');
        card.className = 'draft-card';
        card.innerHTML = `
            <div class="draft-info">
                <h3>Target Category: ${data.targetCategory || 'General'}</h3>
                <p>Generated by ${data.createdBy} on ${dateStr} &bull; ${data.recipients?.length || 0} households evaluated.</p>
            </div>
            <div>
                <span class="draft-status">${data.status}</span>
                <button class="btn btn-outline btn-sm" style="margin-left: 1rem;" data-id="${id}">
                    Review Draft
                </button>
            </div>
        `;

        // Attach listener to review button
        card.querySelector('button').addEventListener('click', () => {
            openDraftDetails(id, data);
        });

        container.appendChild(card);
    });

    if (typeof lucide !== 'undefined') lucide.createIcons();
}

// Render the details of a specific draft
function openDraftDetails(draftId, data) {
    currentDraftId = draftId;
    const detailsView = document.getElementById('draftDetailsView');
    const warning = document.getElementById('exceptionWarning');
    const approveBtn = document.getElementById('approveBtn');

    // Reset state
    warning.style.display = 'none';
    approveBtn.disabled = false;

    document.getElementById('detailTitle').textContent = `Draft Review: ${data.targetCategory}`;

    const recipients = data.recipients || [];
    recipientsPaginator.update(recipients, { resetLimit: true });

    // EXCEPTION SUB-ROUTINE: Check the whole draft (not just the visible page) for
    // corrupted or missing mandatory attributes
    const hasExceptions = recipients.some(r => !r.name || !r.ic || r.income === null || r.dependents === null);
    if (hasExceptions) {
        warning.style.display = 'flex';
        approveBtn.disabled = true;
        approveBtn.title = "Cannot approve a draft containing incomplete profiles.";
    }

    detailsView.classList.add('active');

    // Smooth scroll to details
    detailsView.scrollIntoView({ behavior: 'smooth' });
}

// Render a paginated slice of the draft recipients table
function renderRecipientRows(visible) {
    const tbody = document.getElementById('draftRecipientsBody');
    if (!tbody) return;

    tbody.innerHTML = '';

    if (visible.length === 0) {
        tbody.innerHTML = '<tr><td colspan="4" style="text-align: center; color: #94a3b8;">No recipients found in this draft.</td></tr>';
        return;
    }

    visible.forEach((resident, index) => {
        const tr = document.createElement('tr');

        // Check for corrupted or missing mandatory attributes
        const isCorrupted = !resident.name || !resident.ic || resident.income === null || resident.dependents === null;

        if (isCorrupted) {
            tr.classList.add('incomplete-row');
        }

        const priorityBadge = resident.isPriority
            ? '<span style="color: #ef4444; font-weight: 700;">High Priority</span>'
            : '<span style="color: #64748b; font-weight: 500;">Standard</span>';

        tr.innerHTML = `
            <td style="font-weight: 700;">#${index + 1}</td>
            <td>
                <strong style="color: #0f172a;">${resident.name || '<span style="color:red">[MISSING NAME]</span>'}</strong>
                <br><small style="color: #64748b; font-family: monospace;">IC: ${resident.ic || '<span style="color:red">[MISSING IC]</span>'}</small>
                ${isCorrupted ? '<br><span style="color:#ef4444; font-size:0.75rem; font-weight:700;">⚠️ INCOMPLETE PROFILE - REQUIRES MANUAL REMEDIATION</span>' : ''}
            </td>
            <td>
                <div style="font-size: 0.85rem;">
                    <strong>Income:</strong> RM ${resident.income ?? 'N/A'}<br>
                    <strong>Per Capita:</strong> RM ${(resident.perCapita ?? 0).toFixed(2)}<br>
                    <strong>Status:</strong> ${priorityBadge}
                </div>
            </td>
            <td>
                <div class="xai-log">
                    ${resident.xaiLog || 'No explanation generated.'}
                </div>
            </td>
        `;
        tbody.appendChild(tr);
    });
}

function closeDetails() {
    document.getElementById('draftDetailsView').classList.remove('active');
    currentDraftId = null;
}

// Update document status in Firestore
async function updateDraftStatus(newStatus) {
    if (!currentDraftId) return;

    try {
        // Update Firestore
        const docRef = doc(db, "welfareDrafts", currentDraftId);
        await updateDoc(docRef, {
            status: newStatus,
            updatedAt: new Date().toISOString()
        });

        // Show Success Banner
        const banner = document.getElementById('successBanner');
        banner.style.display = 'flex';
        banner.querySelector('span').textContent = `Draft successfully marked as: ${newStatus}`;
        
        // Hide banner after 3 seconds
        setTimeout(() => {
            banner.style.display = 'none';
        }, 3000);

        // Close details and refresh list
        closeDetails();
        await fetchPendingDrafts();

    } catch (error) {
        console.error("Error updating status:", error);
        alert(`Failed to update status: ${error.message}`);
    }
}
